name: application pipeline
on:
  push:
    branches:
      - master
jobs:
  run-build-test:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write

    name: Build and tests application code and updates archives to s3
    steps:
      # confirms the value of ${{vars.PROJECT_NAME}} is 'burnday'
      - name: validate-project-name
        run: |
          set -e
          if [ ${{vars.PROJECT_NAME}} != 'burnday' ]; then
              echo "Project name is not 'burnday'"
              exit 1
          fi
      - name: checkout-current-branch
        uses: actions/checkout@v4
